services:
  diary:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - GB_USERS=test@example.com:JDJhJDEwJC9sVWJpTlBYVlZvcU9ZNUxIZmhqYi4vUnRuVkJNaEw4MTQ2VUdFSXRDeE9Ib0ZoVkRLR3pl
      - GB_DBPATH=/data/diary.db
      - GB_ASSETPATH=/data/diary-assets
    volumes:
      - ${DATA:-/tmp/diary.data}:/data
